name: 功能需求
description: 提出一个需求/改进建议
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        建议先说明你的使用场景与约束（macOS/Linux、目标客户端、是否必须默认启用、是否能接受交互）。

  - type: textarea
    id: problem
    attributes:
      label: 你遇到的问题/痛点是什么？
      description: “现在做不到什么”或“现在做起来很麻烦什么”
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 你希望如何改进？
      description: 如果你已经有大致方案/交互形态，请描述一下
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 有没有替代方案/变通方式？
      description: 你目前是怎么绕过去的？

  - type: dropdown
    id: impact
    attributes:
      label: 影响范围
      options:
        - 只影响某一个客户端
        - 影响多个客户端
        - 影响核心架构/中央清单
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 其他补充
      description: 例如：是否愿意提交 PR、是否有时间窗口、是否涉及兼容性要求
